# Pandas 基礎教學 2｜股票日成交資訊

台灣證券交易所-個股日成交資訊：<br>
https://www.twse.com.tw/zh/page/trading/exchange/STOCK_DAY.html

In [1]:
import requests

url = 'https://www.twse.com.tw/exchangeReport/STOCK_DAY'

payloads = {
    'response': 'html',
    'date': '20200601',
    'stockNo': '1101'
}

headers = {
    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36'
}

response = requests.get(url, headers=headers, params=payloads)

In [3]:
response.text

'<!doctype html>\n<html lang="zh">\n<head>\n  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n  <meta http-equiv="X-UA-Compatible" content="IE=edge">\n  <title>TWSE 臺灣證券交易所 - 報表</title>\n  <style>\n    table { border-collapse: collapse; margin: 1em 0; }\n    table, th, td { border: 1px solid lightgray; }\n    table thead th, table thead td { text-align: center; background-color: #eee; }\n    table thead div { font-size: 20px; padding: 10px; }\n    table tbody tr:nth-child(even){ background-color:#f8f8f8; }\n    td { padding: 4px; }\n    td>p { margin: 0; text-align: center; }\n    div.notes { margin: 2em 0 4em 0; line-height: 1.5em; }\n    table tbody td { text-align: right; }\n    table tbody td:first-child { text-align: center; }\n    table tbody td:first-child + td { text-align: left; }\n  </style>\n</head>\n<body>\n<div>\n    \n        <table>\n            <thead>\n            <tr>\n                <th colspan=\'9\'>\n                    <div>109年03月 1101 台泥             各日成交資訊</div>\n                </th>\n            </tr>\n            \n            <tr>\n                \n                    <td>日期</td>\n                \n                    <td>成交股數</td>\n                \n                    <td>成交金額</td>\n                \n                    <td>開盤價</td>\n                \n                    <td>最高價</td>\n                \n                    <td>最低價</td>\n                \n                    <td>收盤價</td>\n                \n                    <td>漲跌價差</td>\n                \n                    <td>成交筆數</td>\n                \n            </tr>\n            </thead>\n            <tbody>\n            \n                <tr>\n                    \n                        <td>109/03/02</td>\n                    \n                        <td>19,464,670</td>\n                    \n                        <td>820,634,945</td>\n                    \n                        <td>41.40</td>\n                    \n                        <td>42.60</td>\n                    \n                        <td>41.40</td>\n                    \n                        <td>42.25</td>\n                    \n                        <td> 0.00</td>\n                    \n                        <td>6,713</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/03</td>\n                    \n                        <td>14,474,150</td>\n                    \n                        <td>618,431,178</td>\n                    \n                        <td>42.60</td>\n                    \n                        <td>42.90</td>\n                    \n                        <td>42.50</td>\n                    \n                        <td>42.65</td>\n                    \n                        <td>+0.40</td>\n                    \n                        <td>4,446</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/04</td>\n                    \n                        <td>9,537,433</td>\n                    \n                        <td>408,263,824</td>\n                    \n                        <td>42.60</td>\n                    \n                        <td>42.95</td>\n                    \n                        <td>42.60</td>\n                    \n                        <td>42.85</td>\n                    \n                        <td>+0.20</td>\n                    \n                        <td>3,002</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/05</td>\n                    \n                        <td>10,483,070</td>\n                    \n                        <td>451,950,451</td>\n                    \n                        <td>42.90</td>\n                    \n                        <td>43.30</td>\n                    \n                        <td>42.85</td>\n                    \n                        <td>43.30</td>\n                    \n                        <td>+0.45</td>\n                    \n                        <td>4,048</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/06</td>\n                    \n                        <td>13,206,384</td>\n                    \n                        <td>566,064,257</td>\n                    \n                        <td>43.20</td>\n                    \n                        <td>43.20</td>\n                    \n                        <td>42.50</td>\n                    \n                        <td>42.85</td>\n                    \n                        <td>-0.45</td>\n                    \n                        <td>4,208</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/09</td>\n                    \n                        <td>21,445,731</td>\n                    \n                        <td>901,372,833</td>\n                    \n                        <td>42.20</td>\n                    \n                        <td>42.40</td>\n                    \n                        <td>41.70</td>\n                    \n                        <td>41.85</td>\n                    \n                        <td>-1.00</td>\n                    \n                        <td>7,179</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/10</td>\n                    \n                        <td>18,373,010</td>\n                    \n                        <td>763,447,320</td>\n                    \n                        <td>41.20</td>\n                    \n                        <td>41.90</td>\n                    \n                        <td>41.20</td>\n                    \n                        <td>41.60</td>\n                    \n                        <td>-0.25</td>\n                    \n                        <td>6,656</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/11</td>\n                    \n                        <td>15,028,516</td>\n                    \n                        <td>630,516,266</td>\n                    \n                        <td>42.00</td>\n                    \n                        <td>42.25</td>\n                    \n                        <td>41.70</td>\n                    \n                        <td>41.80</td>\n                    \n                        <td>+0.20</td>\n                    \n                        <td>5,633</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/12</td>\n                    \n                        <td>29,637,367</td>\n                    \n                        <td>1,215,770,160</td>\n                    \n                        <td>41.70</td>\n                    \n                        <td>41.80</td>\n                    \n                        <td>40.40</td>\n                    \n                        <td>40.75</td>\n                    \n                        <td>-1.05</td>\n                    \n                        <td>10,800</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/13</td>\n                    \n                        <td>42,284,434</td>\n                    \n                        <td>1,653,643,838</td>\n                    \n                        <td>39.00</td>\n                    \n                        <td>40.55</td>\n                    \n                        <td>38.30</td>\n                    \n                        <td>40.25</td>\n                    \n                        <td>-0.50</td>\n                    \n                        <td>14,369</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/16</td>\n                    \n                        <td>20,548,943</td>\n                    \n                        <td>811,674,382</td>\n                    \n                        <td>40.25</td>\n                    \n                        <td>40.25</td>\n                    \n                        <td>38.85</td>\n                    \n                        <td>38.85</td>\n                    \n                        <td>-1.40</td>\n                    \n                        <td>7,705</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/17</td>\n                    \n                        <td>43,649,794</td>\n                    \n                        <td>1,649,530,268</td>\n                    \n                        <td>38.00</td>\n                    \n                        <td>38.20</td>\n                    \n                        <td>37.45</td>\n                    \n                        <td>37.60</td>\n                    \n                        <td>-1.25</td>\n                    \n                        <td>13,944</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/18</td>\n                    \n                        <td>36,467,777</td>\n                    \n                        <td>1,343,606,922</td>\n                    \n                        <td>37.30</td>\n                    \n                        <td>37.50</td>\n                    \n                        <td>36.00</td>\n                    \n                        <td>36.00</td>\n                    \n                        <td>-1.60</td>\n                    \n                        <td>15,058</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/19</td>\n                    \n                        <td>36,658,794</td>\n                    \n                        <td>1,251,104,218</td>\n                    \n                        <td>34.90</td>\n                    \n                        <td>34.90</td>\n                    \n                        <td>33.35</td>\n                    \n                        <td>33.60</td>\n                    \n                        <td>-2.40</td>\n                    \n                        <td>16,611</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/20</td>\n                    \n                        <td>32,820,319</td>\n                    \n                        <td>1,184,241,762</td>\n                    \n                        <td>34.15</td>\n                    \n                        <td>36.95</td>\n                    \n                        <td>34.15</td>\n                    \n                        <td>36.95</td>\n                    \n                        <td>+3.35</td>\n                    \n                        <td>11,214</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/23</td>\n                    \n                        <td>30,694,697</td>\n                    \n                        <td>1,107,450,069</td>\n                    \n                        <td>35.80</td>\n                    \n                        <td>36.95</td>\n                    \n                        <td>34.50</td>\n                    \n                        <td>36.10</td>\n                    \n                        <td>-0.85</td>\n                    \n                        <td>8,200</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/24</td>\n                    \n                        <td>23,929,371</td>\n                    \n                        <td>915,895,081</td>\n                    \n                        <td>38.30</td>\n                    \n                        <td>38.70</td>\n                    \n                        <td>37.80</td>\n                    \n                        <td>38.25</td>\n                    \n                        <td>+2.15</td>\n                    \n                        <td>9,572</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/25</td>\n                    \n                        <td>17,956,597</td>\n                    \n                        <td>701,750,294</td>\n                    \n                        <td>39.05</td>\n                    \n                        <td>39.50</td>\n                    \n                        <td>38.70</td>\n                    \n                        <td>38.80</td>\n                    \n                        <td>+0.55</td>\n                    \n                        <td>7,400</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/26</td>\n                    \n                        <td>17,364,088</td>\n                    \n                        <td>676,632,258</td>\n                    \n                        <td>39.50</td>\n                    \n                        <td>39.50</td>\n                    \n                        <td>38.55</td>\n                    \n                        <td>38.60</td>\n                    \n                        <td>-0.20</td>\n                    \n                        <td>5,675</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/27</td>\n                    \n                        <td>14,154,796</td>\n                    \n                        <td>553,157,694</td>\n                    \n                        <td>39.30</td>\n                    \n                        <td>39.45</td>\n                    \n                        <td>38.80</td>\n                    \n                        <td>38.95</td>\n                    \n                        <td>+0.35</td>\n                    \n                        <td>4,980</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/30</td>\n                    \n                        <td>11,479,147</td>\n                    \n                        <td>445,447,560</td>\n                    \n                        <td>38.25</td>\n                    \n                        <td>39.20</td>\n                    \n                        <td>38.00</td>\n                    \n                        <td>39.15</td>\n                    \n                        <td>+0.20</td>\n                    \n                        <td>4,593</td>\n                    \n                </tr>\n            \n                <tr>\n                    \n                        <td>109/03/31</td>\n                    \n                        <td>17,002,298</td>\n                    \n                        <td>668,791,722</td>\n                    \n                        <td>39.25</td>\n                    \n                        <td>39.50</td>\n                    \n                        <td>39.00</td>\n                    \n                        <td>39.50</td>\n                    \n                        <td>+0.35</td>\n                    \n                        <td>5,348</td>\n                    \n                </tr>\n            \n            </tbody>\n        </table>\n\n        \n            <div class="notes">\n                \n                \n                    \n                        <b>說明：</b>\n                    \n                    <ol>\n                        \n                            <li>符號說明:+/-/X表示漲/跌/不比價</li>\n                        \n                            <li>當日統計資訊含一般、零股、盤後定價、鉅額交易，不含拍賣、標購。</li>\n                        \n                            <li>ETF證券代號第六碼為K、M、S、C者，表示該ETF以外幣交易。</li>\n                        \n                    </ol>\n                \n            </div>\n        \n    \n\n</div>\n</body>\n</html>'

In [2]:
import pandas as pd

pd.read_html(response.text)

[   109年06月 1101 台泥 各日成交資訊                                                    \
                        日期      成交股數        成交金額    開盤價    最高價    最低價    收盤價
 0               109/06/01  13078634   563016744  42.95  43.15  42.75  43.10
 1               109/06/02  12568609   543078464  43.15  43.30  43.05  43.30
 2               109/06/03  18791075   820378010  43.50  43.90  43.40  43.65
 3               109/06/04  13868624   603196516  44.00  44.00  43.30  43.40
 4               109/06/05   8873983   386149271  43.50  43.65  43.35  43.65
 5               109/06/08  15341602   670784440  43.75  43.95  43.50  43.95
 6               109/06/09  14104400   617295643  43.65  43.90  43.60  43.90
 7               109/06/10  22750386   999014263  43.75  44.15  43.50  44.00
 8               109/06/11  16466320   719101496  43.90  44.05  43.30  43.30
 9               109/06/12  21783848   933217214  42.50  43.00  42.45  42.90
 10              109/06/15  17874614   762470767  42.75  42.95  42.50  42.50
 11              109/06/16  11897301   510156938  42.75  43.15  42.70  42.85
 12              109/06/17  14696654   626818544  42.80  42.85  42.55  42.85
 13              109/06/18  10558799   450935298  42.85  42.90  42.60  42.70
 14              109/06/19  25125556  1073041829  42.80  43.20  42.55  42.55
 15              109/06/22  12590838   538775823  42.85  43.10  42.65  42.90
 16              109/06/23  14116429   604267273  43.00  43.00  42.70  42.70
 17              109/06/24  14382227   615991311  42.90  43.00  42.70  42.85
 18              109/06/29  13244414   565549779  42.60  42.85  42.60  42.65
 19              109/06/30  12448715   532833070  42.90  42.90  42.75  42.75


     漲跌價差  成交筆數
 0   0.55  6028
 1   0.20  6184
 2   0.35  8453
 3  -0.25  6031
 4   0.25  4817
 5   0.30  5785
 6  -0.05  6513
 7   0.10  9742
 8  -0.70  9121
 9  -0.40  8779
 10 -0.40  8950
 11  0.35  8204
 12  0.00  8539
 13 -0.15  6118
 14 -0.15  9486
 15  0.35  6717
 16 -0.20  7036
 17  0.15  8189
 18 -0.20  5813
 19  0.10  4973  ]

In [3]:
df = pd.read_html(response.text)[0]
df

   109年06月 1101 台泥 各日成交資訊                                                    \
                       日期      成交股數        成交金額    開盤價    最高價    最低價    收盤價
0               109/06/01  13078634   563016744  42.95  43.15  42.75  43.10
1               109/06/02  12568609   543078464  43.15  43.30  43.05  43.30
2               109/06/03  18791075   820378010  43.50  43.90  43.40  43.65
3               109/06/04  13868624   603196516  44.00  44.00  43.30  43.40
4               109/06/05   8873983   386149271  43.50  43.65  43.35  43.65
5               109/06/08  15341602   670784440  43.75  43.95  43.50  43.95
6               109/06/09  14104400   617295643  43.65  43.90  43.60  43.90
7               109/06/10  22750386   999014263  43.75  44.15  43.50  44.00
8               109/06/11  16466320   719101496  43.90  44.05  43.30  43.30
9               109/06/12  21783848   933217214  42.50  43.00  42.45  42.90
10              109/06/15  17874614   762470767  42.75  42.95  42.50  42.50
11              109/06/16  11897301   510156938  42.75  43.15  42.70  42.85
12              109/06/17  14696654   626818544  42.80  42.85  42.55  42.85
13              109/06/18  10558799   450935298  42.85  42.90  42.60  42.70
14              109/06/19  25125556  1073041829  42.80  43.20  42.55  42.55
15              109/06/22  12590838   538775823  42.85  43.10  42.65  42.90
16              109/06/23  14116429   604267273  43.00  43.00  42.70  42.70
17              109/06/24  14382227   615991311  42.90  43.00  42.70  42.85
18              109/06/29  13244414   565549779  42.60  42.85  42.60  42.65
19              109/06/30  12448715   532833070  42.90  42.90  42.75  42.75


    漲跌價差  成交筆數
0   0.55  6028
1   0.20  6184
2   0.35  8453
3  -0.25  6031
4   0.25  4817
5   0.30  5785
6  -0.05  6513
7   0.10  9742
8  -0.70  9121
9  -0.40  8779
10 -0.40  8950
11  0.35  8204
12  0.00  8539
13 -0.15  6118
14 -0.15  9486
15  0.35  6717
16 -0.20  7036
17  0.15  8189
18 -0.20  5813
19  0.10  4973

In [5]:
df.columns = df.columns.droplevel(0)

ValueError: Cannot remove 1 levels from an index with 1 levels: at least one level must be left.

In [6]:
df

           日期      成交股數        成交金額    開盤價    最高價    最低價    收盤價  漲跌價差  成交筆數
0   109/06/01  13078634   563016744  42.95  43.15  42.75  43.10  0.55  6028
1   109/06/02  12568609   543078464  43.15  43.30  43.05  43.30  0.20  6184
2   109/06/03  18791075   820378010  43.50  43.90  43.40  43.65  0.35  8453
3   109/06/04  13868624   603196516  44.00  44.00  43.30  43.40 -0.25  6031
4   109/06/05   8873983   386149271  43.50  43.65  43.35  43.65  0.25  4817
5   109/06/08  15341602   670784440  43.75  43.95  43.50  43.95  0.30  5785
6   109/06/09  14104400   617295643  43.65  43.90  43.60  43.90 -0.05  6513
7   109/06/10  22750386   999014263  43.75  44.15  43.50  44.00  0.10  9742
8   109/06/11  16466320   719101496  43.90  44.05  43.30  43.30 -0.70  9121
9   109/06/12  21783848   933217214  42.50  43.00  42.45  42.90 -0.40  8779
10  109/06/15  17874614   762470767  42.75  42.95  42.50  42.50 -0.40  8950
11  109/06/16  11897301   510156938  42.75  43.15  42.70  42.85  0.35  8204
12  109/06/17  14696654   626818544  42.80  42.85  42.55  42.85  0.00  8539
13  109/06/18  10558799   450935298  42.85  42.90  42.60  42.70 -0.15  6118
14  109/06/19  25125556  1073041829  42.80  43.20  42.55  42.55 -0.15  9486
15  109/06/22  12590838   538775823  42.85  43.10  42.65  42.90  0.35  6717
16  109/06/23  14116429   604267273  43.00  43.00  42.70  42.70 -0.20  7036
17  109/06/24  14382227   615991311  42.90  43.00  42.70  42.85  0.15  8189
18  109/06/29  13244414   565549779  42.60  42.85  42.60  42.65 -0.20  5813
19  109/06/30  12448715   532833070  42.90  42.90  42.75  42.75  0.10  4973

In [7]:
def convert_date(date):
    
    year = date.split('/', 1)[0]
    month_day = date.split('/', 1)[1]
    
    return '{}/{}'.format(int(year) + 1911, month_day)

In [9]:
convert_date('109/06/31')

'2020/03/31'

In [10]:
df['日期'] = df['日期'].apply(convert_date)
df

            日期      成交股數        成交金額    開盤價    最高價    最低價    收盤價  漲跌價差   成交筆數
0   2020/03/02  19464670   820634945  41.40  42.60  41.40  42.25  0.00   6713
1   2020/03/03  14474150   618431178  42.60  42.90  42.50  42.65  0.40   4446
2   2020/03/04   9537433   408263824  42.60  42.95  42.60  42.85  0.20   3002
3   2020/03/05  10483070   451950451  42.90  43.30  42.85  43.30  0.45   4048
4   2020/03/06  13206384   566064257  43.20  43.20  42.50  42.85 -0.45   4208
5   2020/03/09  21445731   901372833  42.20  42.40  41.70  41.85 -1.00   7179
6   2020/03/10  18373010   763447320  41.20  41.90  41.20  41.60 -0.25   6656
7   2020/03/11  15028516   630516266  42.00  42.25  41.70  41.80  0.20   5633
8   2020/03/12  29637367  1215770160  41.70  41.80  40.40  40.75 -1.05  10800
9   2020/03/13  42284434  1653643838  39.00  40.55  38.30  40.25 -0.50  14369
10  2020/03/16  20548943   811674382  40.25  40.25  38.85  38.85 -1.40   7705
11  2020/03/17  43649794  1649530268  38.00  38.20  37.45  37.60 -1.25  13944
12  2020/03/18  36467777  1343606922  37.30  37.50  36.00  36.00 -1.60  15058
13  2020/03/19  36658794  1251104218  34.90  34.90  33.35  33.60 -2.40  16611
14  2020/03/20  32820319  1184241762  34.15  36.95  34.15  36.95  3.35  11214
15  2020/03/23  30694697  1107450069  35.80  36.95  34.50  36.10 -0.85   8200
16  2020/03/24  23929371   915895081  38.30  38.70  37.80  38.25  2.15   9572
17  2020/03/25  17956597   701750294  39.05  39.50  38.70  38.80  0.55   7400
18  2020/03/26  17364088   676632258  39.50  39.50  38.55  38.60 -0.20   5675
19  2020/03/27  14154796   553157694  39.30  39.45  38.80  38.95  0.35   4980
20  2020/03/30  11479147   445447560  38.25  39.20  38.00  39.15  0.20   4593
21  2020/03/31  17002298   668791722  39.25  39.50  39.00  39.50  0.35   5348

In [15]:
df['日期'] = df['日期'].apply(lambda date: '{}/{}'.format(int(date.split('/', 1)[0]) + 1911, date.split('/', 1)[1]))

In [16]:
df

            日期      成交股數        成交金額    開盤價    最高價    最低價    收盤價  漲跌價差   成交筆數
0   2020/03/02  19464670   820634945  41.40  42.60  41.40  42.25  0.00   6713
1   2020/03/03  14474150   618431178  42.60  42.90  42.50  42.65  0.40   4446
2   2020/03/04   9537433   408263824  42.60  42.95  42.60  42.85  0.20   3002
3   2020/03/05  10483070   451950451  42.90  43.30  42.85  43.30  0.45   4048
4   2020/03/06  13206384   566064257  43.20  43.20  42.50  42.85 -0.45   4208
5   2020/03/09  21445731   901372833  42.20  42.40  41.70  41.85 -1.00   7179
6   2020/03/10  18373010   763447320  41.20  41.90  41.20  41.60 -0.25   6656
7   2020/03/11  15028516   630516266  42.00  42.25  41.70  41.80  0.20   5633
8   2020/03/12  29637367  1215770160  41.70  41.80  40.40  40.75 -1.05  10800
9   2020/03/13  42284434  1653643838  39.00  40.55  38.30  40.25 -0.50  14369
10  2020/03/16  20548943   811674382  40.25  40.25  38.85  38.85 -1.40   7705
11  2020/03/17  43649794  1649530268  38.00  38.20  37.45  37.60 -1.25  13944
12  2020/03/18  36467777  1343606922  37.30  37.50  36.00  36.00 -1.60  15058
13  2020/03/19  36658794  1251104218  34.90  34.90  33.35  33.60 -2.40  16611
14  2020/03/20  32820319  1184241762  34.15  36.95  34.15  36.95  3.35  11214
15  2020/03/23  30694697  1107450069  35.80  36.95  34.50  36.10 -0.85   8200
16  2020/03/24  23929371   915895081  38.30  38.70  37.80  38.25  2.15   9572
17  2020/03/25  17956597   701750294  39.05  39.50  38.70  38.80  0.55   7400
18  2020/03/26  17364088   676632258  39.50  39.50  38.55  38.60 -0.20   5675
19  2020/03/27  14154796   553157694  39.30  39.45  38.80  38.95  0.35   4980
20  2020/03/30  11479147   445447560  38.25  39.20  38.00  39.15  0.20   4593
21  2020/03/31  17002298   668791722  39.25  39.50  39.00  39.50  0.35   5348

In [17]:
df.set_index('日期', inplace=True)

In [18]:
df

                成交股數        成交金額    開盤價    最高價    最低價    收盤價  漲跌價差   成交筆數
日期
2020/03/02  19464670   820634945  41.40  42.60  41.40  42.25  0.00   6713
2020/03/03  14474150   618431178  42.60  42.90  42.50  42.65  0.40   4446
2020/03/04   9537433   408263824  42.60  42.95  42.60  42.85  0.20   3002
2020/03/05  10483070   451950451  42.90  43.30  42.85  43.30  0.45   4048
2020/03/06  13206384   566064257  43.20  43.20  42.50  42.85 -0.45   4208
2020/03/09  21445731   901372833  42.20  42.40  41.70  41.85 -1.00   7179
2020/03/10  18373010   763447320  41.20  41.90  41.20  41.60 -0.25   6656
2020/03/11  15028516   630516266  42.00  42.25  41.70  41.80  0.20   5633
2020/03/12  29637367  1215770160  41.70  41.80  40.40  40.75 -1.05  10800
2020/03/13  42284434  1653643838  39.00  40.55  38.30  40.25 -0.50  14369
2020/03/16  20548943   811674382  40.25  40.25  38.85  38.85 -1.40   7705
2020/03/17  43649794  1649530268  38.00  38.20  37.45  37.60 -1.25  13944
2020/03/18  36467777  1343606922  37.30  37.50  36.00  36.00 -1.60  15058
2020/03/19  36658794  1251104218  34.90  34.90  33.35  33.60 -2.40  16611
2020/03/20  32820319  1184241762  34.15  36.95  34.15  36.95  3.35  11214
2020/03/23  30694697  1107450069  35.80  36.95  34.50  36.10 -0.85   8200
2020/03/24  23929371   915895081  38.30  38.70  37.80  38.25  2.15   9572
2020/03/25  17956597   701750294  39.05  39.50  38.70  38.80  0.55   7400
2020/03/26  17364088   676632258  39.50  39.50  38.55  38.60 -0.20   5675
2020/03/27  14154796   553157694  39.30  39.45  38.80  38.95  0.35   4980
2020/03/30  11479147   445447560  38.25  39.20  38.00  39.15  0.20   4593
2020/03/31  17002298   668791722  39.25  39.50  39.00  39.50  0.35   5348

In [19]:
df.to_csv('1101-各日成交資訊.csv', encoding='utf-8')

In [20]:
df_from_csv = pd.read_csv('1101-各日成交資訊.csv', index_col='日期', parse_dates=['日期'])
df_from_csv

                成交股數        成交金額    開盤價    最高價    最低價    收盤價  漲跌價差   成交筆數
日期
2020-03-02  19464670   820634945  41.40  42.60  41.40  42.25  0.00   6713
2020-03-03  14474150   618431178  42.60  42.90  42.50  42.65  0.40   4446
2020-03-04   9537433   408263824  42.60  42.95  42.60  42.85  0.20   3002
2020-03-05  10483070   451950451  42.90  43.30  42.85  43.30  0.45   4048
2020-03-06  13206384   566064257  43.20  43.20  42.50  42.85 -0.45   4208
2020-03-09  21445731   901372833  42.20  42.40  41.70  41.85 -1.00   7179
2020-03-10  18373010   763447320  41.20  41.90  41.20  41.60 -0.25   6656
2020-03-11  15028516   630516266  42.00  42.25  41.70  41.80  0.20   5633
2020-03-12  29637367  1215770160  41.70  41.80  40.40  40.75 -1.05  10800
2020-03-13  42284434  1653643838  39.00  40.55  38.30  40.25 -0.50  14369
2020-03-16  20548943   811674382  40.25  40.25  38.85  38.85 -1.40   7705
2020-03-17  43649794  1649530268  38.00  38.20  37.45  37.60 -1.25  13944
2020-03-18  36467777  1343606922  37.30  37.50  36.00  36.00 -1.60  15058
2020-03-19  36658794  1251104218  34.90  34.90  33.35  33.60 -2.40  16611
2020-03-20  32820319  1184241762  34.15  36.95  34.15  36.95  3.35  11214
2020-03-23  30694697  1107450069  35.80  36.95  34.50  36.10 -0.85   8200
2020-03-24  23929371   915895081  38.30  38.70  37.80  38.25  2.15   9572
2020-03-25  17956597   701750294  39.05  39.50  38.70  38.80  0.55   7400
2020-03-26  17364088   676632258  39.50  39.50  38.55  38.60 -0.20   5675
2020-03-27  14154796   553157694  39.30  39.45  38.80  38.95  0.35   4980
2020-03-30  11479147   445447560  38.25  39.20  38.00  39.15  0.20   4593
2020-03-31  17002298   668791722  39.25  39.50  39.00  39.50  0.35   5348

In [21]:
import sqlite3

connection = sqlite3.connect('各日成交資訊.db')

df.to_sql('stock', connection, if_exists='replace')

In [22]:
df_from_db = pd.read_sql('SELECT * FROM stock', connection, index_col='日期', parse_dates=['日期'])
df_from_db

                成交股數        成交金額    開盤價    最高價    最低價    收盤價  漲跌價差   成交筆數
日期
2020-03-02  19464670   820634945  41.40  42.60  41.40  42.25  0.00   6713
2020-03-03  14474150   618431178  42.60  42.90  42.50  42.65  0.40   4446
2020-03-04   9537433   408263824  42.60  42.95  42.60  42.85  0.20   3002
2020-03-05  10483070   451950451  42.90  43.30  42.85  43.30  0.45   4048
2020-03-06  13206384   566064257  43.20  43.20  42.50  42.85 -0.45   4208
2020-03-09  21445731   901372833  42.20  42.40  41.70  41.85 -1.00   7179
2020-03-10  18373010   763447320  41.20  41.90  41.20  41.60 -0.25   6656
2020-03-11  15028516   630516266  42.00  42.25  41.70  41.80  0.20   5633
2020-03-12  29637367  1215770160  41.70  41.80  40.40  40.75 -1.05  10800
2020-03-13  42284434  1653643838  39.00  40.55  38.30  40.25 -0.50  14369
2020-03-16  20548943   811674382  40.25  40.25  38.85  38.85 -1.40   7705
2020-03-17  43649794  1649530268  38.00  38.20  37.45  37.60 -1.25  13944
2020-03-18  36467777  1343606922  37.30  37.50  36.00  36.00 -1.60  15058
2020-03-19  36658794  1251104218  34.90  34.90  33.35  33.60 -2.40  16611
2020-03-20  32820319  1184241762  34.15  36.95  34.15  36.95  3.35  11214
2020-03-23  30694697  1107450069  35.80  36.95  34.50  36.10 -0.85   8200
2020-03-24  23929371   915895081  38.30  38.70  37.80  38.25  2.15   9572
2020-03-25  17956597   701750294  39.05  39.50  38.70  38.80  0.55   7400
2020-03-26  17364088   676632258  39.50  39.50  38.55  38.60 -0.20   5675
2020-03-27  14154796   553157694  39.30  39.45  38.80  38.95  0.35   4980
2020-03-30  11479147   445447560  38.25  39.20  38.00  39.15  0.20   4593
2020-03-31  17002298   668791722  39.25  39.50  39.00  39.50  0.35   5348

In [1]:
import time
import requests
import pandas as pd
import sqlite3

def get_daily_prices(date):
    
    url = 'https://www.twse.com.tw/exchangeReport/STOCK_DAY'

    payloads = {
        'response': 'html',
        'date': date,
        'stockNo': 1101
    }

    headers = {
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36'
    }

    response = requests.get(url, headers=headers, params=payloads)
    
    df = pd.read_html(response.text)[0]
    df.columns = df.columns.droplevel(0)
    df['日期'] = df['日期'].apply(lambda date: '{}/{}'.format(int(date.split('/', 1)[0]) + 1911, date.split('/', 1)[1]))
    df.set_index('日期', inplace=True)
    
    time.sleep(5)
    
    return df


def save_to_db(new_df):
    
    connection = sqlite3.connect('各日成交資訊2.db')
    
    try:
        df = pd.read_sql('SELECT * FROM stock', connection, index_col='日期')
    except:
        df = pd.DataFrame()
    
    combined_df = df.append(new_df, sort=False)
    
    final_df = combined_df.reset_index().drop_duplicates(subset=['日期'], keep='last').set_index(['日期']).sort_index()   
    
    final_df.to_sql('stock', connection, if_exists='replace')
    
    connection.close()
    
    return final_df

In [2]:
df = get_daily_prices('20200101')
df

                成交股數        成交金額    開盤價    最高價    最低價    收盤價  漲跌價差   成交筆數
日期
2020/01/02  18470566   813465904  43.80  44.15  43.80  44.10  0.40   6251
2020/01/03  18387114   807459827  44.15  44.25  43.45  43.95 -0.15   6733
2020/01/06  13867625   602752323  43.50  43.70  43.30  43.45 -0.50   5566
2020/01/07  14185347   616059913  43.45  43.60  43.20  43.60  0.15   4739
2020/01/08  13465670   583893343  43.15  43.55  43.15  43.40 -0.20   4685
2020/01/09  17899047   777095165  43.40  43.60  43.30  43.45  0.05   4299
2020/01/10  12755874   554204406  43.45  43.50  43.35  43.50  0.05   3188
2020/01/13  23870603  1051194288  43.75  44.25  43.65  44.25  0.75   6532
2020/01/14  20357664   904504264  44.25  44.55  44.25  44.55  0.30   5770
2020/01/15  23662867  1053815288  44.55  44.70  44.30  44.55  0.00   7657
2020/01/16  14814952   662036531  44.50  44.95  44.45  44.75  0.20   5776
2020/01/17   9522761   426564174  44.90  44.90  44.65  44.90  0.15   4164
2020/01/20   8870270   398481034  44.95  45.00  44.85  44.95  0.05   3320
2020/01/30  64150715  2725362280  42.70  43.05  41.60  41.85 -3.10  19930
2020/01/31  26430159  1116222284  41.75  42.50  41.75  42.05  0.20   8709

In [3]:
final_df = save_to_db(df)
final_df

                成交股數        成交金額    開盤價    最高價    最低價    收盤價  漲跌價差   成交筆數
日期
2020/01/02  18470566   813465904  43.80  44.15  43.80  44.10  0.40   6251
2020/01/03  18387114   807459827  44.15  44.25  43.45  43.95 -0.15   6733
2020/01/06  13867625   602752323  43.50  43.70  43.30  43.45 -0.50   5566
2020/01/07  14185347   616059913  43.45  43.60  43.20  43.60  0.15   4739
2020/01/08  13465670   583893343  43.15  43.55  43.15  43.40 -0.20   4685
2020/01/09  17899047   777095165  43.40  43.60  43.30  43.45  0.05   4299
2020/01/10  12755874   554204406  43.45  43.50  43.35  43.50  0.05   3188
2020/01/13  23870603  1051194288  43.75  44.25  43.65  44.25  0.75   6532
2020/01/14  20357664   904504264  44.25  44.55  44.25  44.55  0.30   5770
2020/01/15  23662867  1053815288  44.55  44.70  44.30  44.55  0.00   7657
2020/01/16  14814952   662036531  44.50  44.95  44.45  44.75  0.20   5776
2020/01/17   9522761   426564174  44.90  44.90  44.65  44.90  0.15   4164
2020/01/20   8870270   398481034  44.95  45.00  44.85  44.95  0.05   3320
2020/01/30  64150715  2725362280  42.70  43.05  41.60  41.85 -3.10  19930
2020/01/31  26430159  1116222284  41.75  42.50  41.75  42.05  0.20   8709
2020/02/03  23001298   942583933  40.50  41.65  40.10  41.55 -0.50   8088
2020/02/04  20790788   878703530  41.60  42.70  41.60  42.40  0.85   8133
2020/02/05  15228671   644977888  42.50  42.65  41.95  42.35 -0.05   5257
2020/02/06  14063043   603883999  42.50  43.10  42.45  43.00  0.65   4029
2020/02/07  13537254   574693939  42.20  42.70  42.05  42.50 -0.50   4510
2020/02/10  12820414   541670664  42.00  42.60  41.70  42.40 -0.10   4073
2020/02/11  15825702   675999276  42.50  42.90  42.50  42.60  0.20   4608
2020/02/12  14367529   615124852  42.60  43.00  42.60  42.80  0.20   3855
2020/02/13  18326337   790906891  42.80  43.45  42.80  43.15  0.35   6489
2020/02/14   9297256   402285311  43.20  43.40  43.15  43.20  0.05   3502
2020/02/17  10347058   444890344  42.80  43.10  42.75  43.00 -0.20   3109
2020/02/18   9220879   396963797  43.00  43.20  42.90  43.05  0.05   2509
2020/02/19  12463648   539911116  43.10  43.50  43.10  43.40  0.35   4144
2020/02/20  10840090   470884644  43.55  43.80  43.15  43.15 -0.25   3693
2020/02/21  10565795   456575839  43.15  43.35  43.05  43.25  0.10   2771
2020/02/24  12606292   541934056  43.00  43.20  42.80  43.00 -0.25   4073
2020/02/25  17268484   737292511  42.35  43.00  42.30  42.70 -0.30   7454
2020/02/26  20869167   883113162  42.15  42.60  42.10  42.20 -0.50   6656
2020/02/27  15386463   650149283  42.20  42.40  42.05  42.25  0.05   5246
2020/03/02  19464670   820634945  41.40  42.60  41.40  42.25  0.00   6713
2020/03/03  14474150   618431178  42.60  42.90  42.50  42.65  0.40   4446
2020/03/04   9537433   408263824  42.60  42.95  42.60  42.85  0.20   3002
2020/03/05  10483070   451950451  42.90  43.30  42.85  43.30  0.45   4048
2020/03/06  13206384   566064257  43.20  43.20  42.50  42.85 -0.45   4208
2020/03/09  21445731   901372833  42.20  42.40  41.70  41.85 -1.00   7179
2020/03/10  18373010   763447320  41.20  41.90  41.20  41.60 -0.25   6656
2020/03/11  15028516   630516266  42.00  42.25  41.70  41.80  0.20   5633
2020/03/12  29637367  1215770160  41.70  41.80  40.40  40.75 -1.05  10800
2020/03/13  42284434  1653643838  39.00  40.55  38.30  40.25 -0.50  14369
2020/03/16  20548943   811674382  40.25  40.25  38.85  38.85 -1.40   7705
2020/03/17  43649794  1649530268  38.00  38.20  37.45  37.60 -1.25  13944
2020/03/18  36467777  1343606922  37.30  37.50  36.00  36.00 -1.60  15058
2020/03/19  36658794  1251104218  34.90  34.90  33.35  33.60 -2.40  16611
2020/03/20  32820319  1184241762  34.15  36.95  34.15  36.95  3.35  11214
2020/03/23  30694697  1107450069  35.80  36.95  34.50  36.10 -0.85   8200
2020/03/24  23929371   915895081  38.30  38.70  37.80  38.25  2.15   9572
2020/03/25  17956597   701750294  39.05  39.50  38.70  38.80  0.55   7400
2020/03/26  17364088   676632258  39.50  39.50  38.55  38.60 -0.20   5675
2020/03/27  14154796   553157694  39.30  39.45  38.80  38.95  0.35   4980
2020/03/30  11479147   445447560  38.25  39.20  38.00  39.15  0.20   4593
2020/03/31  17002298   668791722  39.25  39.50  39.00  39.50  0.35   5348