# 台灣證券交易所｜每日收盤行情資訊
台灣證券交易所：https://www.twse.com.tw/zh/

In [1]:
import requests
import pandas as pd

date = '20200302'

url = 'https://www.twse.com.tw/exchangeReport/MI_INDEX'

payloads = {
    'response': 'html',
    'date': date,
    'type': 'ALLBUT0999'
}

headers = {
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'
}

response = requests.get(url, headers=headers, params=payloads)

In [2]:
df = pd.read_html(response.text)[-1]
df

     109年03月02日每日收盤行情(全部(不含權證、牛熊證))                                        \
                              (元,股)
                               證券代號     證券名稱      成交股數   成交筆數        成交金額
0                              0050   元大台灣50  27894641  12628  2437814508
1                              0051  元大中型100     44100     31     1462989
2                              0052     富邦科技    179121     76    11997207
3                              0053     元大電子      9010      9      352073
4                              0054   元大台商50      1000      1       22660
...                             ...      ...       ...    ...         ...
1106                           9944       新麗   2934347   1571    66093782
1107                           9945      潤泰新   2275791   1380    93730984
1108                           9946     三發地產   1790850    828    35957550
1109                           9955       佳龍   1151810    633    21334985
1110                           9958      世紀鋼  14262330   8577  1098669094

                                                                              \
                                               (元,交易單位)
        開盤價    最高價    最低價    收盤價 漲跌(+/-)  漲跌價差   最後揭示買價 最後揭示買量 最後揭示賣價 最後揭示賣量
0     87.50  88.25  86.85  87.35       -  1.30    87.30    272  87.35    100
1     33.24  33.42  32.78  33.23       -  0.26    33.20      2  33.23     27
2     66.25  67.50  66.10  66.85       -  1.05    66.85      1  66.90      2
3     38.85  39.21  38.85  38.98       -  0.46    38.98      1  39.01      3
4     22.66  22.66  22.66  22.66       -  0.39    22.50      4  22.59      3
...     ...    ...    ...    ...     ...   ...      ...    ...    ...    ...
1106  22.75  23.40  22.20  22.45       +  0.55    22.45     15  22.50     15
1107  40.55  41.95  40.50  41.15       +  0.10    41.15     13  41.20      7
1108  20.00  20.50  19.75  20.00       -  0.65    19.95     88  20.05     16
1109  18.50  18.85  18.40  18.50       -  0.80    18.50     13  18.55     11
1110  74.00  79.10  72.90  79.00       +  5.40    78.90      6  79.00     12



         本益比
0       0.00
1       0.00
2       0.00
3       0.00
4       0.00
...      ...
1106    0.00
1107    3.79
1108    4.06
1109  115.62
1110   27.34

[1111 rows x 16 columns]

In [3]:
df.columns = df.columns.get_level_values(2)
df

,證券代號,證券名稱,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌(+/-),漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
0,0050,元大台灣50,27894641,12628,2437814508,87.50,88.25,86.85,87.35,-,1.30,87.30,272,87.35,100,0.00
1,0051,元大中型100,44100,31,1462989,33.24,33.42,32.78,33.23,-,0.26,33.20,2,33.23,27,0.00
2,0052,富邦科技,179121,76,11997207,66.25,67.50,66.10,66.85,-,1.05,66.85,1,66.90,2,0.00
3,0053,元大電子,9010,9,352073,38.85,39.21,38.85,38.98,-,0.46,38.98,1,39.01,3,0.00
4,0054,元大台商50,1000,1,22660,22.66,22.66,22.66,22.66,-,0.39,22.50,4,22.59,3,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106,9944,新麗,2934347,1571,66093782,22.75,23.40,22.20,22.45,+,0.55,22.45,15,22.50,15,0.00
1107,9945,潤泰新,2275791,1380,93730984,40.55,41.95,40.50,41.15,+,0.10,41.15,13,41.20,7,3.79
1108,9946,三發地產,1790850,828,35957550,20.00,20.50,19.75,20.00,-,0.65,19.95,88,20.05,16,4.06
1109,9955,佳龍,1151810,633,21334985,18.50,18.85,18.40,18.50,-,0.80,18.50,13,18.55,11,115.62
1110,9958,世紀鋼,14262330,8577,1098669094,74.00,79.10,72.90,79.00,+,5.40,78.90,6,79.00,12,27.34

In [4]:
df.drop(['證券名稱', '漲跌(+/-)'], axis=1, inplace=True)
df

,證券代號,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
0,0050,27894641,12628,2437814508,87.50,88.25,86.85,87.35,1.30,87.30,272,87.35,100,0.00
1,0051,44100,31,1462989,33.24,33.42,32.78,33.23,0.26,33.20,2,33.23,27,0.00
2,0052,179121,76,11997207,66.25,67.50,66.10,66.85,1.05,66.85,1,66.90,2,0.00
3,0053,9010,9,352073,38.85,39.21,38.85,38.98,0.46,38.98,1,39.01,3,0.00
4,0054,1000,1,22660,22.66,22.66,22.66,22.66,0.39,22.50,4,22.59,3,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106,9944,2934347,1571,66093782,22.75,23.40,22.20,22.45,0.55,22.45,15,22.50,15,0.00
1107,9945,2275791,1380,93730984,40.55,41.95,40.50,41.15,0.10,41.15,13,41.20,7,3.79
1108,9946,1790850,828,35957550,20.00,20.50,19.75,20.00,0.65,19.95,88,20.05,16,4.06
1109,9955,1151810,633,21334985,18.50,18.85,18.40,18.50,0.80,18.50,13,18.55,11,115.62
1110,9958,14262330,8577,1098669094,74.00,79.10,72.90,79.00,5.40,78.90,6,79.00,12,27.34

In [5]:
df['日期'] = pd.to_datetime(date)
df

,證券代號,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比,日期
0,0050,27894641,12628,2437814508,87.50,88.25,86.85,87.35,1.30,87.30,272,87.35,100,0.00,2020-03-02
1,0051,44100,31,1462989,33.24,33.42,32.78,33.23,0.26,33.20,2,33.23,27,0.00,2020-03-02
2,0052,179121,76,11997207,66.25,67.50,66.10,66.85,1.05,66.85,1,66.90,2,0.00,2020-03-02
3,0053,9010,9,352073,38.85,39.21,38.85,38.98,0.46,38.98,1,39.01,3,0.00,2020-03-02
4,0054,1000,1,22660,22.66,22.66,22.66,22.66,0.39,22.50,4,22.59,3,0.00,2020-03-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1106,9944,2934347,1571,66093782,22.75,23.40,22.20,22.45,0.55,22.45,15,22.50,15,0.00,2020-03-02
1107,9945,2275791,1380,93730984,40.55,41.95,40.50,41.15,0.10,41.15,13,41.20,7,3.79,2020-03-02
1108,9946,1790850,828,35957550,20.00,20.50,19.75,20.00,0.65,19.95,88,20.05,16,4.06,2020-03-02
1109,9955,1151810,633,21334985,18.50,18.85,18.40,18.50,0.80,18.50,13,18.55,11,115.62,2020-03-02
1110,9958,14262330,8577,1098669094,74.00,79.10,72.90,79.00,5.40,78.90,6,79.00,12,27.34,2020-03-02

In [6]:
df = df.set_index(['證券代號', '日期'])
df

,,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
證券代號,日期,,,,,,,,,,,,,
0050,2020-03-02,27894641,12628,2437814508,87.50,88.25,86.85,87.35,1.30,87.30,272,87.35,100,0.00
0051,2020-03-02,44100,31,1462989,33.24,33.42,32.78,33.23,0.26,33.20,2,33.23,27,0.00
0052,2020-03-02,179121,76,11997207,66.25,67.50,66.10,66.85,1.05,66.85,1,66.90,2,0.00
0053,2020-03-02,9010,9,352073,38.85,39.21,38.85,38.98,0.46,38.98,1,39.01,3,0.00
0054,2020-03-02,1000,1,22660,22.66,22.66,22.66,22.66,0.39,22.50,4,22.59,3,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9944,2020-03-02,2934347,1571,66093782,22.75,23.40,22.20,22.45,0.55,22.45,15,22.50,15,0.00
9945,2020-03-02,2275791,1380,93730984,40.55,41.95,40.50,41.15,0.10,41.15,13,41.20,7,3.79
9946,2020-03-02,1790850,828,35957550,20.00,20.50,19.75,20.00,0.65,19.95,88,20.05,16,4.06
9955,2020-03-02,1151810,633,21334985,18.50,18.85,18.40,18.50,0.80,18.50,13,18.55,11,115.62
9958,2020-03-02,14262330,8577,1098669094,74.00,79.10,72.90,79.00,5.40,78.90,6,79.00,12,27.34

In [7]:
df.loc['00643K']

,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
日期,,,,,,,,,,,,,
2020-03-02,0,0,0,--,--,--,--,0.0,3.51,2,3.59,2,0.0

In [8]:
df = df.apply(pd.to_numeric, errors='coerce')
df

,,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
證券代號,日期,,,,,,,,,,,,,
0050,2020-03-02,27894641,12628,2437814508,87.50,88.25,86.85,87.35,1.30,87.30,272,87.35,100,0.00
0051,2020-03-02,44100,31,1462989,33.24,33.42,32.78,33.23,0.26,33.20,2,33.23,27,0.00
0052,2020-03-02,179121,76,11997207,66.25,67.50,66.10,66.85,1.05,66.85,1,66.90,2,0.00
0053,2020-03-02,9010,9,352073,38.85,39.21,38.85,38.98,0.46,38.98,1,39.01,3,0.00
0054,2020-03-02,1000,1,22660,22.66,22.66,22.66,22.66,0.39,22.50,4,22.59,3,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9944,2020-03-02,2934347,1571,66093782,22.75,23.40,22.20,22.45,0.55,22.45,15,22.50,15,0.00
9945,2020-03-02,2275791,1380,93730984,40.55,41.95,40.50,41.15,0.10,41.15,13,41.20,7,3.79
9946,2020-03-02,1790850,828,35957550,20.00,20.50,19.75,20.00,0.65,19.95,88,20.05,16,4.06
9955,2020-03-02,1151810,633,21334985,18.50,18.85,18.40,18.50,0.80,18.50,13,18.55,11,115.62
9958,2020-03-02,14262330,8577,1098669094,74.00,79.10,72.90,79.00,5.40,78.90,6,79.00,12,27.34

In [9]:
df[df['收盤價'].isnull()]

,,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
證券代號,日期,,,,,,,,,,,,,
00643K,2020-03-02,0,0,0,NaN,NaN,NaN,NaN,0.0,3.51,2,3.59,2,0.0
00774C,2020-03-02,0,0,0,NaN,NaN,NaN,NaN,0.0,9.34,25,9.37,10,0.0
020002,2020-03-02,0,0,0,NaN,NaN,NaN,NaN,0.0,14.57,499,14.59,355,0.0
020004,2020-03-02,0,0,0,NaN,NaN,NaN,NaN,0.0,21.97,499,21.98,449,0.0
020005,2020-03-02,0,0,0,NaN,NaN,NaN,NaN,0.0,21.16,499,21.18,499,0.0
020006,2020-03-02,0,0,0,NaN,NaN,NaN,NaN,0.0,20.62,325,20.63,301,0.0
020007,2020-03-02,0,0,0,NaN,NaN,NaN,NaN,0.0,21.04,203,21.07,266,0.0
1470,2020-03-02,0,0,0,NaN,NaN,NaN,NaN,0.0,20.05,1,21.25,2,22.5
6225,2020-03-02,0,0,0,NaN,NaN,NaN,NaN,0.0,2.00,1,2.20,26,0.0
911622,2020-03-02,0,0,0,NaN,NaN,NaN,NaN,0.0,10.90,2,11.50,1,0.0

In [10]:
df.drop(df[df['收盤價'].isnull()].index, inplace=True)
df

,,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
證券代號,日期,,,,,,,,,,,,,
0050,2020-03-02,27894641,12628,2437814508,87.50,88.25,86.85,87.35,1.30,87.30,272,87.35,100,0.00
0051,2020-03-02,44100,31,1462989,33.24,33.42,32.78,33.23,0.26,33.20,2,33.23,27,0.00
0052,2020-03-02,179121,76,11997207,66.25,67.50,66.10,66.85,1.05,66.85,1,66.90,2,0.00
0053,2020-03-02,9010,9,352073,38.85,39.21,38.85,38.98,0.46,38.98,1,39.01,3,0.00
0054,2020-03-02,1000,1,22660,22.66,22.66,22.66,22.66,0.39,22.50,4,22.59,3,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9944,2020-03-02,2934347,1571,66093782,22.75,23.40,22.20,22.45,0.55,22.45,15,22.50,15,0.00
9945,2020-03-02,2275791,1380,93730984,40.55,41.95,40.50,41.15,0.10,41.15,13,41.20,7,3.79
9946,2020-03-02,1790850,828,35957550,20.00,20.50,19.75,20.00,0.65,19.95,88,20.05,16,4.06
9955,2020-03-02,1151810,633,21334985,18.50,18.85,18.40,18.50,0.80,18.50,13,18.55,11,115.62
9958,2020-03-02,14262330,8577,1098669094,74.00,79.10,72.90,79.00,5.40,78.90,6,79.00,12,27.34

In [16]:
import requests
import pandas as pd
import sqlite3
import os


def get_daily_prices(date):
        
    url = 'https://www.twse.com.tw/exchangeReport/MI_INDEX'
    
    payloads = {
        'response': 'html',
        'date': date,
        'type': 'ALLBUT0999'
    }
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36'
    }
    
    response = requests.get(url, headers=headers, params=payloads)
    
    try:
        df = pd.read_html(response.text)[-1]
    except:
        return None
    
    df.columns = df.columns.get_level_values(2)
    
    df.drop(['證券名稱', '漲跌(+/-)'], inplace=True, axis=1)
    
    df['日期'] = pd.to_datetime(date)
    
    df = df.set_index(['證券代號', '日期'])
    
    df = df.apply(pd.to_numeric, errors='coerce')
    
    df.drop(df[df['收盤價'].isnull()].index, inplace=True)
    
    return df

def save_daily_prices(new_df):
    
    connection = sqlite3.connect('data.db')
    
    try:
        df = pd.read_sql('select * from daily_prices', connection, parse_dates=['日期'], index_col=['證券代號', '日期'])
    except:
        df = pd.DataFrame()
    
    combined_df = df.append(new_df, sort=False) 
    
    final_df = combined_df.reset_index().drop_duplicates(subset=['證券代號', '日期'], keep='last').set_index(['證券代號', '日期']).sort_index()
    
    final_df.to_sql('daily_prices', connection, if_exists='replace')
    
    connection.close()
    
    excel_file = os.path.join('data',
                              'excel_files',
                              'daily_prices.xlsx')
    
    os.makedirs(os.path.dirname(excel_file), exist_ok=True)
    
    final_df.to_excel(excel_file)

In [14]:
df = get_daily_prices('20200303')
df

,,成交股數,成交筆數,成交金額,開盤價,最高價,最低價,收盤價,漲跌價差,最後揭示買價,最後揭示買量,最後揭示賣價,最後揭示賣量,本益比
證券代號,日期,,,,,,,,,,,,,
0050,2020-03-03,11071900,5903,980838153,88.85,88.95,88.25,88.60,1.25,88.55,62,88.60,260,0.00
0051,2020-03-03,17550,18,590658,33.90,33.90,33.45,33.45,0.22,33.45,12,33.69,17,0.00
0052,2020-03-03,252382,72,17279752,67.50,68.75,67.50,68.45,1.60,68.30,1,68.45,9,0.00
0053,2020-03-03,16000,10,636280,39.70,40.00,39.70,39.75,0.77,39.74,1,39.75,4,0.00
0054,2020-03-03,13000,4,297070,22.83,23.00,22.83,22.84,0.18,22.76,28,22.90,10,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9944,2020-03-03,2031413,969,44484562,22.25,22.30,21.55,21.70,0.75,21.70,23,21.75,11,0.00
9945,2020-03-03,1345864,986,56093468,41.60,41.95,41.55,41.65,0.50,41.60,38,41.65,6,3.84
9946,2020-03-03,956136,451,19386230,20.55,20.60,20.05,20.10,0.10,20.10,29,20.15,15,4.09
9955,2020-03-03,709203,411,13019664,18.70,18.70,18.20,18.20,0.30,18.20,25,18.30,1,113.75
9958,2020-03-03,9747731,5622,767515382,80.20,80.70,77.30,78.10,0.90,78.10,8,78.20,32,27.02

In [17]:
save_daily_prices(df)